name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Build and deploy to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          ssh $VPS_USERNAME@$VPS_HOST 'cd $DEPLOY_PATH && git pull origin main'
          ssh $VPS_USERNAME@$VPS_HOST 'cd $DEPLOY_PATH && docker-compose down'
          ssh $VPS_USERNAME@$VPS_HOST 'cd $DEPLOY_PATH && docker-compose build'
          ssh $VPS_USERNAME@$VPS_HOST 'cd $DEPLOY_PATH && docker-compose up -d'