name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /home/www/simple-chat
            git pull origin main
            docker build -t simple-chat .
            docker stop simple-chat || true
            docker rm simple-chat || true
            docker run -d \
              --name simple-chat \
              --restart unless-stopped \
              -p 3000:3000 \
              simple-chat