name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # Create directory if it doesn't exist
            mkdir -p /home/www/archipelago-test
            cd /home/www/archipelago-test

            # Check if .git directory exists
            if [ ! -d ".git" ]; then
              # Clone repository if it doesn't exist
              git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/andresuch/archipelago-test.git .
            else
              # Pull latest changes if repo exists
              git pull https://${{ secrets.GITHUB_TOKEN }}@github.com/andresuch/archipelago-test.git main
            fi

            # Continue with Docker operations
            docker build -t archipelago-test .
            docker stop archipelago-test || true
            docker rm archipelago-test || true
            docker run -d \
              --name archipelago-test \
              --restart unless-stopped \
              -p 3000:3000 \
              archipelago-test