name: Deploy to S3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        working-directory: ./chat-app
        run: npm install
        
      - name: Build
        working-directory: ./chat-app
        env:
          VITE_SOCKET_HOST: ${{ secrets.VITE_SOCKET_HOST }}
          VITE_AVATAR_URL: ${{ secrets.VITE_AVATAR_URL }}
        run: npm run build
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Deploy to S3
        working-directory: ./chat-app
        run: aws s3 sync dist/ s3://${{ secrets.AWS_BUCKET_NAME }}